name: cached_video_player
description: A new flutter plugin that is virtually a clone of official video_player plugin except that it supports caching( Android and iOS)
version: 2.0.4+1
homepage: https://github.com/vikram25897/flutter_cached_video_player

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.lazyarts.vikram.cached_video_player
        pluginClass: CachedVideoPlayerPlugin
      ios:
        pluginClass: CachedVideoPlayerPlugin
      web:
        default_package: video_player_web

dependencies:
  flutter:
    sdk: flutter

  video_player_platform_interface: ^6.2.3

  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint. The exact value doesn't matter since
  # the constraints on the interface pins it.
  # TODO(amirh): Revisit this (either update this part in the design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  pedantic: ^1.11.1
  pigeon: ^22.5.0
